version: '3.8'
services:
  # airquality-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #   # command: sh -c "chmod a+x ./start-app.sh && ./start-app.sh"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  mongo:
    container_name: mongo-db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - '27017:27017'

  redis:
    container_name: cache
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes:
      - redis:/data





